### ISSUE TITLE
Building tests not possible under MSYS2 + gcc 5.3.0

### ISSUE THREAD

**Issue by mmaurus** [envire/envire-envire_core#17]
A missing semicolon in test_envire_graph, line 510 prevents the tests from compiling.
Further, I get a lot of undefined references to envire in link phase.

It would also be nice to make the tests optional in cmake.

**Comment by arneboe** [comment]
You get that error because there was a semicolon missing. No idea why it compiles on gcc 4.8.4 without problems. Maybe boost specializes the macros for different compiler versions. Anyhow, it is fixed now.
