### ISSUE TITLE
Typo in Graph

### ISSUE THREAD

**Issue by AlexanderFabisch** [envire/envire-envire_core#23]
There is a function called [breathFirstSearch](https://github.com/envire/envire-envire_core/blob/master/src/graph/Graph.hpp#L290)() (d is missing). Seems like the graph is drowning? :)

**Comment by arneboe** [comment]
yes, under the hood the graph is a whale that needs to breath occasionally. You should call this method before performing longer searches. Otherwise the whale might drown while searching.

**Comment by AlexanderFabisch** [comment]
That makes sense. :) Reminds me of [The Beast Below](https://en.wikipedia.org/wiki/The_Beast_Below).

**Comment by arneboe** [comment]
seriously though, I dont know if we can rename the method. It might be used in a lot of places?

**Comment by chhtz** [comment]
We could rename the method and add an deprecated alias with the old name

**Comment by AlexanderFabisch** [comment]
That's what I would suggest. Probably there is some C++ magic to generate compiler warnings if the old method is used and you can print some runtime warning.

**Comment by arneboe** [comment]
[[deprecated]] is available in c++14. can we bump envire to c++14? :)

**Comment by chhtz** [comment]
gcc/clang have ` __attribute__((deprecated))`. MSVC has `__declspec(deprecated)`. These are the alternatives [`EIGEN_DEPRECATED`](https://bitbucket.org/eigen/eigen/src/18be685e28cb85615f5404560cf11290c8ffdab5/Eigen/src/Core/util/Macros.h?at=default&fileviewer=file-view-default#Macros.h-609) currently evaluates to.

**Comment by arneboe** [comment]
`EIGEN_DEPRECATED` sounds good

**Comment by chhtz** [comment]
Fixed: https://github.com/envire/envire-envire_core/commit/ff8d7685fba495c52dc9b9fad1b7794869eabd41
