### ISSUE TITLE
Sectioin for Question and Answers in the Wiki?

### ISSUE THREAD

**Issue by Rauldg** [envire/envire-envire_core#26]
Shall we put in the wiki a section for Questions and Answers?

An example of a question would be:

How do I check if a frame exists in the graph?

Answer: 

Use [containsFrame](https://github.com/envire/envire-envire_core/blob/master/src/graph/Graph.hpp#L135)

**Comment by Rauldg** [comment]
We could use [stack exchange robotics](https://robotics.stackexchange.com/) for this

**Comment by arneboe** [comment]
The tutorials section on envire.github.io already naswres similar questions.

In my opinion we shouldn't split the documentation.

**Comment by Rauldg** [comment]
Actually if the answer is in the tutorials then the answer should be just a link to the correspondent tutorial. I this kind of tool would be very helpful for someone using the tool. Maybe the Wiki is not the nicest place. We have the askbot typically for this but as Envire is open, I think the platform for this questions and asnwers should also be open.

**Comment by arneboe** [comment]
Maybe the best idea would be to just put the whole documentation and 
tutorials into the readme.md and remove it from the envire website.

I dont really see a reason to have the website as additional resource if 
all the info that is displayed on the website can just as well be 
written in the readme. The readme is markdown formatted, thus all the 
usual stuff like images, links, table of contents, etc. works just fine.


In reality nobody is going to update the website ever again. If we put 
the content in the readme at least it is easy to find and might get updated.

what do you think?

**Comment by chhtz** [comment]
I agree on reducing the number of resources which we want to maintain. For the API documentation it would actually be nice to get some auto-generated doxygen documentation (the current documentation at http://envire.github.io/packages/ is (mostly?) a mixture of blind-text, 404 and empty tables)

**Comment by Rauldg** [comment]
About the website, if nobody is responsible of its maintenance, then IMO it should disappear indeed.

Doxygen documentation is also good but still not as effective I think as the questions and answers approach for short to-the-point questions.

Questions and Answers is not the same as documentation. People may ask things with different wording and concepts can also be explained there. Furthermore rights to push on the repository are not required as they are for changing or improving the documentation.  

For the case of the questions and answers, it is self maintained by the users like in stack exchange so it should not suppose much work for us.
