### ISSUE TITLE
ClassLoader throws exception on destruction

### ISSUE THREAD

**Issue by arneboe** [envire/envire-envire_core#37]
The destructor of  ``ClassLoader`` crashes throwing ``class_loader::LibraryUnloadException``.

console output:
```
terminate called after throwing an instance of 'class_loader::LibraryUnloadException'
  what():  Attempt to unload library that class_loader is unaware of.
Aborted (core dumped)

```

Minimal example to reproduce.
```
#include <envire_core/plugin/ClassLoader.hpp>
#include <envire_core/items/Item.hpp>
#include <octomap/AbstractOcTree.h>
using namespace envire::core;

int main(int argc, char **argv)
{
  
  Item<boost::shared_ptr<octomap::AbstractOcTree>>::Ptr octree;
  
  ClassLoader* loader = ClassLoader::getInstance();
  if(!loader->createEnvireItem("envire::core::Item<boost::shared_ptr<octomap::AbstractOcTree>>",octree))
  {
    std::cerr << "Unabled to load envire::octomap::OcTree" << std::endl;
    return -1;
  }
  return 0;
}
```

**Comment by arneboe** [comment]
@saarnold

**Comment by Rauldg** [comment]
Maybe is related to [this one](https://github.com/envire/tools-plugin_manager/issues/1), which also occurs on destruction.

**Comment by arneboe** [comment]
Assertions are disabled in release mode. The assert you found might be a completely different bug. Maybe it is best to open a new bug report for the assert?

**Comment by Rauldg** [comment]
Created the [separated issue](https://github.com/envire/envire-envire_core/issues/39)

**Comment by arneboe** [comment]
After fixing #39 I can no longer reproduce this bug.
