### ISSUE TITLE
install_dependencies.sh fails not being able to recreate its source directories

### ISSUE THREAD

**Issue by pierrewillenbrockdfki** [envire/envire-envire_core#49]
Steps to reproduce:
* use install_dependecies.sh on a unmodified ubuntu 16.04 with the required ubuntu packages
* run into the class_loader issue
* fix the class_loader.pc
* rerun install_dependencies.sh

actual error: 
fatal: Zielpfad 'base-cmake' existiert bereits und ist kein leeres Verzeichnis.
which translates to
fatal: destination path 'base-cmake' already exists and is not an empty directory.

suggested changes:
detect the situation and rm -rf the offending directories then git clone or use git pull instead.

**Comment by arneboe** [comment]
Implemented a solution. My bash isn't that great, could you review it?
https://github.com/envire/envire-envire_core/commit/9c8a6a610e5e7c12bb43cb662db064d4037e5867

**Comment by pierrewillenbrockdfki** [comment]
Looks reasonable, seems to work. Only nitpick here are the unquoted variables, which will cause breakage once there are space characters in them. But that would have to go into another issue, the whole script seems to suffer from that.
