### ISSUE TITLE
install_dependencies.sh generates env.sh that will override user environment settings

### ISSUE THREAD

**Issue by pierrewillenbrockdfki** [envire/envire-envire_core#50]
The generated env.sh contains settings like this:
export PATH=/home/user/testing-envire-envire_core/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

while it should better be
export PATH=/home/user/testing-envire-envire_core/install/bin:$PATH

**Comment by arneboe** [comment]
Done
