### ISSUE TITLE
wrong boost-serialization version on 18.04

### ISSUE THREAD

**Issue by arneboe** [envire/envire-envire_core#51]
----
./test_suite: error while loading shared libraries: libboost_serialization.so.1.58.0: cannot open shared object file: No such file or directory
----

On Ubuntu 18.04 libboost_serialization1.62.0 is installed but for some reason envire_core demands 1.58

**Comment by arneboe** [comment]
This is caused by class_loader which seems to have a hard coded dependency on 1.58.0:
----
        libclass_loader.so => /home/arne/git/entern_new/install/lib/libclass_loader.so
            libboost_system.so.1.58.0 => not found
            libPocoFoundation.so.9 => not found
----

**Comment by chhtz** [comment]
Does re-building class_loader help? I don't think there is any hard-coded depedency to version 1.58

**Comment by arneboe** [comment]
My mistake. Had some strange things in LD_LIBRARY_PATH :)
